"use strict";

// Generated from messages.proto by scripts/generate_messages.py.
// Do not edit this file directly.

const crypto = require("crypto");

const SCHEMA = {
    "enums": {
        "STREAM_STATUS": {
            "SUCCESS": 0,
            "CONNECT_REFUSED": 1,
            "CONNECT_TIMEOUT": 2,
            "STREAM_CLOSED": 3,
            "STREAM_DATA": 4,
            "STREAM_ERROR": 5,
            "NEW_CONNECTION": 6,
            "ASYNC_STREAM": 7,
            "NODEID_MISMATCH": 9,
            "INVALID_FLAGS": 10,
            "STREAM_IN_USE": 11,
            "TIMED_OUT": 12
        },
        "SIGNATURE_ALGORITHMS": {
            "SIGNATURE_ALGORITHM_UNSPECIFIED": 0,
            "P256": 100,
            "RSA2048": 200,
            "RSA4096": 201
        },
        "ERROR_CODE": {
            "UNKNOWN_ERROR": 0,
            "UNKNOWN_MESSAGE_TYPE": 1,
            "SIGNATURE_FAILED": 2,
            "UNIMPLEMENTED": 3
        },
        "ENSDORSMENT_STATUS": {
            "ENDORSEMENT_SUCCESS": 0,
            "ENDORSEMENT_FAILED": 1,
            "ENDORSEMENT_CHALLENGE": 2,
            "ENDORSEMENT_INVALID_SIGNATURE": 3,
            "ENDORSEMENT_UNKNOWN_IDENTITY": 4
        },
        "NAME_STATUS": {
            "NAME_SUCCESS": 0,
            "NAME_NOT_FOUND": 1,
            "NAME_DUPLICATE": 2,
            "NAME_ERROR": 3
        }
    },
    "messages": {
        "Uuid": {
            "fields": [
                {
                    "name": "value",
                    "number": 1,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "StreamID": {
            "fields": [
                {
                    "name": "value",
                    "number": 1,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "NodeId": {
            "fields": [
                {
                    "name": "value",
                    "number": 1,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "EndorsementType": {
            "fields": [
                {
                    "name": "value",
                    "number": 1,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "DateTime": {
            "fields": [
                {
                    "name": "milliseconds_since_epoch",
                    "number": 1,
                    "kind": "scalar",
                    "type": "uint64",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "OptionalBool": {
            "fields": [
                {
                    "name": "value",
                    "number": 1,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "StreamReply": {
            "fields": [
                {
                    "name": "stream_id",
                    "number": 1,
                    "kind": "message",
                    "type": "StreamID",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "error",
                    "number": 2,
                    "kind": "enum",
                    "type": "STREAM_STATUS",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "message",
                    "number": 3,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "new_stream_remote_address",
                    "number": 4,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "new_stream_id",
                    "number": 5,
                    "kind": "message",
                    "type": "StreamID",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "stream_error_code",
                    "number": 6,
                    "kind": "scalar",
                    "type": "int32",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "data",
                    "number": 7,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "StreamSend": {
            "fields": [
                {
                    "name": "stream_id",
                    "number": 1,
                    "kind": "message",
                    "type": "StreamID",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "data",
                    "number": 2,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "index",
                    "number": 3,
                    "kind": "scalar",
                    "type": "uint64",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "StreamRecv": {
            "fields": [
                {
                    "name": "stream_id",
                    "number": 1,
                    "kind": "message",
                    "type": "StreamID",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "max_bytes",
                    "number": 2,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "index",
                    "number": 3,
                    "kind": "scalar",
                    "type": "uint64",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "wait_ms",
                    "number": 4,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "StreamClose": {
            "fields": [
                {
                    "name": "stream_id",
                    "number": 1,
                    "kind": "message",
                    "type": "StreamID",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "SignatureBlock": {
            "fields": [
                {
                    "name": "signer",
                    "number": 1,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "algorithm",
                    "number": 2,
                    "kind": "enum",
                    "type": "SIGNATURE_ALGORITHMS",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "signature",
                    "number": 3,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "PublicKey": {
            "fields": [
                {
                    "name": "algorithm",
                    "number": 1,
                    "kind": "enum",
                    "type": "SIGNATURE_ALGORITHMS",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "public_key",
                    "number": 2,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "Endorsement": {
            "fields": [
                {
                    "name": "subject",
                    "number": 1,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "endorsement_service",
                    "number": 2,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "endorsement_type",
                    "number": 3,
                    "kind": "message",
                    "type": "Uuid",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "endorsement_value",
                    "number": 4,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "valid_until",
                    "number": 5,
                    "kind": "message",
                    "type": "DateTime",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "signature",
                    "number": 99,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "Identity": {
            "fields": [
                {
                    "name": "nonce",
                    "number": 1,
                    "kind": "message",
                    "type": "Uuid",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "public_key",
                    "number": 2,
                    "kind": "message",
                    "type": "PublicKey",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ChallengeRequest": {
            "fields": [
                {
                    "name": "nonce",
                    "number": 1,
                    "kind": "message",
                    "type": "Uuid",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "RouteEntry": {
            "fields": [
                {
                    "name": "node_id",
                    "number": 1,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "hops_away",
                    "number": 2,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "last_seen",
                    "number": 3,
                    "kind": "message",
                    "type": "DateTime",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "RouteUpdate": {
            "fields": [
                {
                    "name": "entries",
                    "number": 2,
                    "kind": "message",
                    "type": "RouteEntry",
                    "repeated": true,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "Address": {
            "fields": [
                {
                    "name": "ipv4",
                    "number": 1,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "ipv6",
                    "number": 2,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "AddressRange": {
            "fields": [
                {
                    "name": "start_address",
                    "number": 1,
                    "kind": "message",
                    "type": "Address",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "end_address",
                    "number": 2,
                    "kind": "message",
                    "type": "Address",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "PortRange": {
            "fields": [
                {
                    "name": "start_port",
                    "number": 1,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "end_port",
                    "number": 2,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ResourceTCPConnect": {
            "fields": [
                {
                    "name": "node_id",
                    "number": 1,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "source_addresses",
                    "number": 2,
                    "kind": "message",
                    "type": "Address",
                    "repeated": true,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ResourceTCPListen": {
            "fields": [
                {
                    "name": "node_id",
                    "number": 1,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "listen_address",
                    "number": 2,
                    "kind": "message",
                    "type": "Address",
                    "repeated": true,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "allowed_range",
                    "number": 3,
                    "kind": "message",
                    "type": "PortRange",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ResourceSSHD": {
            "fields": [
                {
                    "name": "node_id",
                    "number": 1,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "server_name",
                    "number": 2,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ResourceRecord": {
            "fields": [
                {
                    "name": "tcp_connect",
                    "number": 1,
                    "kind": "message",
                    "type": "ResourceTCPConnect",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "resource_type"
                },
                {
                    "name": "tcp_listen",
                    "number": 2,
                    "kind": "message",
                    "type": "ResourceTCPListen",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "resource_type"
                },
                {
                    "name": "sshd",
                    "number": 3,
                    "kind": "message",
                    "type": "ResourceSSHD",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "resource_type"
                }
            ],
            "oneofs": [
                {
                    "name": "resource_type",
                    "fields": [
                        "tcp_connect",
                        "tcp_listen",
                        "sshd"
                    ]
                }
            ]
        },
        "ServiceSchema": {
            "fields": [
                {
                    "name": "proto_file_name",
                    "number": 1,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "proto_file_descriptor_set",
                    "number": 2,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "accepted_type_urls",
                    "number": 3,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": true,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "schema_hash",
                    "number": 4,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "schema_version",
                    "number": 5,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "SchemaRequest": {
            "fields": [
                {
                    "name": "proto_file_name",
                    "number": 1,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "schema_hash",
                    "number": 2,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "SchemaReply": {
            "fields": [
                {
                    "name": "schemas",
                    "number": 1,
                    "kind": "message",
                    "type": "ServiceSchema",
                    "repeated": true,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ResourceAdvertisement": {
            "fields": [
                {
                    "name": "records",
                    "number": 1,
                    "kind": "message",
                    "type": "ResourceRecord",
                    "repeated": true,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "schemas",
                    "number": 2,
                    "kind": "message",
                    "type": "ServiceSchema",
                    "repeated": true,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ResourceQuery": {
            "fields": [
                {
                    "name": "query",
                    "number": 1,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "max_records",
                    "number": 2,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "Error": {
            "fields": [
                {
                    "name": "error_code",
                    "number": 1,
                    "kind": "enum",
                    "type": "ERROR_CODE",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "message",
                    "number": 2,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "PingRequest": {
            "fields": [
                {
                    "name": "nonce",
                    "number": 1,
                    "kind": "message",
                    "type": "Uuid",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "sequence",
                    "number": 2,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "time_sent",
                    "number": 3,
                    "kind": "message",
                    "type": "DateTime",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "PingReply": {
            "fields": [
                {
                    "name": "nonce",
                    "number": 1,
                    "kind": "message",
                    "type": "Uuid",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "sequence",
                    "number": 2,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "time_sent",
                    "number": 3,
                    "kind": "message",
                    "type": "DateTime",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "time_replied",
                    "number": 4,
                    "kind": "message",
                    "type": "DateTime",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "BeginEndorsementRequest": {
            "fields": [
                {
                    "name": "requested_values",
                    "number": 1,
                    "kind": "message",
                    "type": "Endorsement",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "auth_data",
                    "number": 2,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "EndorsementChallenge": {
            "fields": [
                {
                    "name": "stage",
                    "number": 1,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "challenge",
                    "number": 2,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "EndorsementChallengeReply": {
            "fields": [
                {
                    "name": "stage",
                    "number": 1,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "challenge_reply",
                    "number": 2,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "EndorsementDone": {
            "fields": [
                {
                    "name": "status",
                    "number": 1,
                    "kind": "enum",
                    "type": "ENSDORSMENT_STATUS",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "new_endorsement",
                    "number": 2,
                    "kind": "message",
                    "type": "Endorsement",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTEquals": {
            "fields": [
                {
                    "name": "lhs",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDAbstractSyntaxTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "rhs",
                    "number": 2,
                    "kind": "message",
                    "type": "ERDAbstractSyntaxTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTAnd": {
            "fields": [
                {
                    "name": "lhs",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDAbstractSyntaxTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "rhs",
                    "number": 2,
                    "kind": "message",
                    "type": "ERDAbstractSyntaxTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTOr": {
            "fields": [
                {
                    "name": "lhs",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDAbstractSyntaxTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "rhs",
                    "number": 2,
                    "kind": "message",
                    "type": "ERDAbstractSyntaxTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTAllOf": {
            "fields": [
                {
                    "name": "terms",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDAbstractSyntaxTree",
                    "repeated": true,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTAnyOf": {
            "fields": [
                {
                    "name": "terms",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDAbstractSyntaxTree",
                    "repeated": true,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTTrue": {
            "fields": [],
            "oneofs": []
        },
        "ERDASTFalse": {
            "fields": [],
            "oneofs": []
        },
        "ERDASTEndEquals": {
            "fields": [
                {
                    "name": "lhs",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDASTEndTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "rhs",
                    "number": 2,
                    "kind": "message",
                    "type": "ERDASTEndTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTEndAnd": {
            "fields": [
                {
                    "name": "lhs",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDASTEndTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "rhs",
                    "number": 2,
                    "kind": "message",
                    "type": "ERDASTEndTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTEndOr": {
            "fields": [
                {
                    "name": "lhs",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDASTEndTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "rhs",
                    "number": 2,
                    "kind": "message",
                    "type": "ERDASTEndTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTEndAllOf": {
            "fields": [
                {
                    "name": "terms",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDASTEndTree",
                    "repeated": true,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTEndAnyOf": {
            "fields": [
                {
                    "name": "terms",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDASTEndTree",
                    "repeated": true,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTEndTypeEquals": {
            "fields": [
                {
                    "name": "type",
                    "number": 1,
                    "kind": "message",
                    "type": "EndorsementType",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTEndValueEquals": {
            "fields": [
                {
                    "name": "value",
                    "number": 1,
                    "kind": "scalar",
                    "type": "bytes",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTEndSignerEquals": {
            "fields": [
                {
                    "name": "signer",
                    "number": 1,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTEndTree": {
            "fields": [
                {
                    "name": "equals",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDASTEndEquals",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "and",
                    "number": 2,
                    "kind": "message",
                    "type": "ERDASTEndAnd",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "or",
                    "number": 3,
                    "kind": "message",
                    "type": "ERDASTEndOr",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "true_value",
                    "number": 9,
                    "kind": "message",
                    "type": "ERDASTTrue",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "false_value",
                    "number": 10,
                    "kind": "message",
                    "type": "ERDASTFalse",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "all_of",
                    "number": 11,
                    "kind": "message",
                    "type": "ERDASTEndAllOf",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "any_of",
                    "number": 12,
                    "kind": "message",
                    "type": "ERDASTEndAnyOf",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "type_equals",
                    "number": 100,
                    "kind": "message",
                    "type": "ERDASTEndTypeEquals",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "value_equals",
                    "number": 101,
                    "kind": "message",
                    "type": "ERDASTEndValueEquals",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "signer_equals",
                    "number": 102,
                    "kind": "message",
                    "type": "ERDASTEndSignerEquals",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                }
            ],
            "oneofs": [
                {
                    "name": "node_type",
                    "fields": [
                        "equals",
                        "and",
                        "or",
                        "true_value",
                        "false_value",
                        "all_of",
                        "any_of",
                        "type_equals",
                        "value_equals",
                        "signer_equals"
                    ]
                }
            ]
        },
        "ERDASTEndorsement": {
            "fields": [
                {
                    "name": "tree",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDASTEndTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTMesEquals": {
            "fields": [
                {
                    "name": "lhs",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDASTMessageTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "rhs",
                    "number": 2,
                    "kind": "message",
                    "type": "ERDASTMessageTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTMesAnd": {
            "fields": [
                {
                    "name": "lhs",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDASTMessageTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "rhs",
                    "number": 2,
                    "kind": "message",
                    "type": "ERDASTMessageTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTMesOr": {
            "fields": [
                {
                    "name": "lhs",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDASTMessageTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "rhs",
                    "number": 2,
                    "kind": "message",
                    "type": "ERDASTMessageTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTMesAllOf": {
            "fields": [
                {
                    "name": "terms",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDASTMessageTree",
                    "repeated": true,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTMesAnyOf": {
            "fields": [
                {
                    "name": "terms",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDASTMessageTree",
                    "repeated": true,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTMesDestination": {
            "fields": [
                {
                    "name": "destination",
                    "number": 1,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTMesSource": {
            "fields": [
                {
                    "name": "source",
                    "number": 1,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDASTMessageTree": {
            "fields": [
                {
                    "name": "equals",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDASTMesEquals",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "and",
                    "number": 2,
                    "kind": "message",
                    "type": "ERDASTMesAnd",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "or",
                    "number": 3,
                    "kind": "message",
                    "type": "ERDASTMesOr",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "true_value",
                    "number": 9,
                    "kind": "message",
                    "type": "ERDASTTrue",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "false_value",
                    "number": 10,
                    "kind": "message",
                    "type": "ERDASTFalse",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "all_of",
                    "number": 11,
                    "kind": "message",
                    "type": "ERDASTMesAllOf",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "any_of",
                    "number": 12,
                    "kind": "message",
                    "type": "ERDASTMesAnyOf",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "destination",
                    "number": 100,
                    "kind": "message",
                    "type": "ERDASTMesDestination",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "source",
                    "number": 101,
                    "kind": "message",
                    "type": "ERDASTMesSource",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                }
            ],
            "oneofs": [
                {
                    "name": "node_type",
                    "fields": [
                        "equals",
                        "and",
                        "or",
                        "true_value",
                        "false_value",
                        "all_of",
                        "any_of",
                        "destination",
                        "source"
                    ]
                }
            ]
        },
        "ERDASTMessage": {
            "fields": [
                {
                    "name": "tree",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDASTMessageTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ERDAbstractSyntaxTree": {
            "fields": [
                {
                    "name": "equals",
                    "number": 1,
                    "kind": "message",
                    "type": "ERDASTEquals",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "and",
                    "number": 2,
                    "kind": "message",
                    "type": "ERDASTAnd",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "or",
                    "number": 3,
                    "kind": "message",
                    "type": "ERDASTOr",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "true_value",
                    "number": 9,
                    "kind": "message",
                    "type": "ERDASTTrue",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "false_value",
                    "number": 10,
                    "kind": "message",
                    "type": "ERDASTFalse",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "all_of",
                    "number": 11,
                    "kind": "message",
                    "type": "ERDASTAllOf",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "any_of",
                    "number": 12,
                    "kind": "message",
                    "type": "ERDASTAnyOf",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "endorsement",
                    "number": 100,
                    "kind": "message",
                    "type": "ERDASTEndorsement",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                },
                {
                    "name": "message",
                    "number": 101,
                    "kind": "message",
                    "type": "ERDASTMessage",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "node_type"
                }
            ],
            "oneofs": [
                {
                    "name": "node_type",
                    "fields": [
                        "equals",
                        "and",
                        "or",
                        "true_value",
                        "false_value",
                        "all_of",
                        "any_of",
                        "endorsement",
                        "message"
                    ]
                }
            ]
        },
        "EndorsementNeeded": {
            "fields": [
                {
                    "name": "message_nonce",
                    "number": 1,
                    "kind": "message",
                    "type": "Uuid",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "tree",
                    "number": 2,
                    "kind": "message",
                    "type": "ERDAbstractSyntaxTree",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "RSPMessage": {
            "fields": [
                {
                    "name": "destination",
                    "number": 1,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "source",
                    "number": 2,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "challenge_request",
                    "number": 3,
                    "kind": "message",
                    "type": "ChallengeRequest",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "core_message"
                },
                {
                    "name": "identity",
                    "number": 4,
                    "kind": "message",
                    "type": "Identity",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "core_message"
                },
                {
                    "name": "route",
                    "number": 5,
                    "kind": "message",
                    "type": "RouteUpdate",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "core_message"
                },
                {
                    "name": "error",
                    "number": 6,
                    "kind": "message",
                    "type": "Error",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "core_message"
                },
                {
                    "name": "ping_request",
                    "number": 7,
                    "kind": "message",
                    "type": "PingRequest",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "core_message"
                },
                {
                    "name": "ping_reply",
                    "number": 8,
                    "kind": "message",
                    "type": "PingReply",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "core_message"
                },
                {
                    "name": "resource_advertisement",
                    "number": 16,
                    "kind": "message",
                    "type": "ResourceAdvertisement",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "core_message"
                },
                {
                    "name": "resource_query",
                    "number": 17,
                    "kind": "message",
                    "type": "ResourceQuery",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "core_message"
                },
                {
                    "name": "nonce",
                    "number": 22,
                    "kind": "message",
                    "type": "Uuid",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "endorsement_needed",
                    "number": 23,
                    "kind": "message",
                    "type": "EndorsementNeeded",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "core_message"
                },
                {
                    "name": "trace",
                    "number": 24,
                    "kind": "message",
                    "type": "OptionalBool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "schema_request",
                    "number": 25,
                    "kind": "message",
                    "type": "SchemaRequest",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "core_message"
                },
                {
                    "name": "schema_reply",
                    "number": 26,
                    "kind": "message",
                    "type": "SchemaReply",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": "core_message"
                },
                {
                    "name": "signature",
                    "number": 99,
                    "kind": "message",
                    "type": "SignatureBlock",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "endorsements",
                    "number": 100,
                    "kind": "message",
                    "type": "Endorsement",
                    "repeated": true,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "identities",
                    "number": 101,
                    "kind": "message",
                    "type": "Identity",
                    "repeated": true,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "service_message",
                    "number": 200,
                    "kind": "message",
                    "type": "Any",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": [
                {
                    "name": "core_message",
                    "fields": [
                        "challenge_request",
                        "identity",
                        "route",
                        "error",
                        "ping_request",
                        "ping_reply",
                        "resource_advertisement",
                        "resource_query",
                        "endorsement_needed",
                        "schema_request",
                        "schema_reply"
                    ]
                }
            ]
        },
        "ConnectTCPRequest": {
            "fields": [
                {
                    "name": "host_port",
                    "number": 1,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "stream_id",
                    "number": 2,
                    "kind": "message",
                    "type": "StreamID",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "reuse_addr",
                    "number": 3,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "source_port",
                    "number": 4,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "timeout_ms",
                    "number": 5,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "retries",
                    "number": 6,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "retry_ms",
                    "number": 7,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "async_data",
                    "number": 8,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "use_socket",
                    "number": 9,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "share_socket",
                    "number": 10,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ListenTCPRequest": {
            "fields": [
                {
                    "name": "host_port",
                    "number": 1,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "stream_id",
                    "number": 2,
                    "kind": "message",
                    "type": "StreamID",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "reuse_addr",
                    "number": 3,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "timeout_ms",
                    "number": 4,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "async_accept",
                    "number": 5,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "share_listening_socket",
                    "number": 6,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "share_child_sockets",
                    "number": 7,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "children_use_socket",
                    "number": 8,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "children_async_data",
                    "number": 9,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "AcceptTCP": {
            "fields": [
                {
                    "name": "listen_stream_id",
                    "number": 1,
                    "kind": "message",
                    "type": "StreamID",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "new_stream_id",
                    "number": 2,
                    "kind": "message",
                    "type": "StreamID",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "timeout_ms",
                    "number": 3,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "share_child_socket",
                    "number": 4,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "child_use_socket",
                    "number": 5,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "child_async_data",
                    "number": 6,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "ConnectSshd": {
            "fields": [
                {
                    "name": "stream_id",
                    "number": 2,
                    "kind": "message",
                    "type": "StreamID",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "timeout_ms",
                    "number": 5,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "async_data",
                    "number": 8,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "use_socket",
                    "number": 9,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "share_socket",
                    "number": 10,
                    "kind": "scalar",
                    "type": "bool",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "NameRecord": {
            "fields": [
                {
                    "name": "name",
                    "number": 1,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "owner",
                    "number": 2,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "type",
                    "number": 3,
                    "kind": "message",
                    "type": "Uuid",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "value",
                    "number": 4,
                    "kind": "message",
                    "type": "Uuid",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "NameCreateRequest": {
            "fields": [
                {
                    "name": "record",
                    "number": 1,
                    "kind": "message",
                    "type": "NameRecord",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "NameCreateReply": {
            "fields": [
                {
                    "name": "status",
                    "number": 1,
                    "kind": "enum",
                    "type": "NAME_STATUS",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "message",
                    "number": 2,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "NameReadRequest": {
            "fields": [
                {
                    "name": "name",
                    "number": 1,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "owner",
                    "number": 2,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "type",
                    "number": 3,
                    "kind": "message",
                    "type": "Uuid",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "NameReadReply": {
            "fields": [
                {
                    "name": "status",
                    "number": 1,
                    "kind": "enum",
                    "type": "NAME_STATUS",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "records",
                    "number": 2,
                    "kind": "message",
                    "type": "NameRecord",
                    "repeated": true,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "NameUpdateRequest": {
            "fields": [
                {
                    "name": "name",
                    "number": 1,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "owner",
                    "number": 2,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "type",
                    "number": 3,
                    "kind": "message",
                    "type": "Uuid",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "new_value",
                    "number": 4,
                    "kind": "message",
                    "type": "Uuid",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "NameUpdateReply": {
            "fields": [
                {
                    "name": "status",
                    "number": 1,
                    "kind": "enum",
                    "type": "NAME_STATUS",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "message",
                    "number": 2,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "NameDeleteRequest": {
            "fields": [
                {
                    "name": "name",
                    "number": 1,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "owner",
                    "number": 2,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "type",
                    "number": 3,
                    "kind": "message",
                    "type": "Uuid",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "NameDeleteReply": {
            "fields": [
                {
                    "name": "status",
                    "number": 1,
                    "kind": "enum",
                    "type": "NAME_STATUS",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                },
                {
                    "name": "message",
                    "number": 2,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "NameQueryRequest": {
            "fields": [
                {
                    "name": "name_prefix",
                    "number": 1,
                    "kind": "scalar",
                    "type": "string",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "owner",
                    "number": 2,
                    "kind": "message",
                    "type": "NodeId",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "type",
                    "number": 3,
                    "kind": "message",
                    "type": "Uuid",
                    "repeated": false,
                    "has_presence": true,
                    "oneof": null
                },
                {
                    "name": "max_records",
                    "number": 4,
                    "kind": "scalar",
                    "type": "uint32",
                    "repeated": false,
                    "has_presence": false,
                    "oneof": null
                }
            ],
            "oneofs": []
        },
        "NameQueryReply": {
            "fields": [
                {
                    "name": "records",
                    "number": 1,
                    "kind": "message",
                    "type": "NameRecord",
                    "repeated": true,
                    "has_presence": true,
                    "oneof": null
                }
            ],
            "oneofs": []
        }
    }
};
const MESSAGE_TYPES = SCHEMA.messages;
const ENUM_TYPES = SCHEMA.enums;
const FIELD_NAME_LOOKUP = new Map(
    Object.entries(MESSAGE_TYPES).map(([typeName, definition]) => [
        typeName,
        new Set(definition.fields.map((field) => field.name)),
    ])
);

function hasOwn(object, key) {
    return Object.prototype.hasOwnProperty.call(object, key);
}

function fieldPresent(object, key) {
    return object !== null && typeof object === "object" && hasOwn(object, key) && object[key] !== undefined && object[key] !== null;
}

function fail(path, message) {
    throw new Error(`${path}: ${message}`);
}

function isPlainObject(value) {
    return value !== null && typeof value === "object" && !Array.isArray(value);
}

function normalizeBytes(value, path) {
    if (Buffer.isBuffer(value) || value instanceof Uint8Array) {
        return Buffer.from(value).toString("base64");
    }
    if (typeof value !== "string") {
        fail(path, "expected bytes as a base64 string, Buffer, or Uint8Array");
    }
    return value;
}

function normalizeBoolean(value, path) {
    if (typeof value !== "boolean") {
        fail(path, "expected a boolean");
    }
    return value;
}

function normalizeString(value, path) {
    if (typeof value !== "string") {
        fail(path, "expected a string");
    }
    return value;
}

function normalizeInteger(value, path, minimum, maximum) {
    let numericValue = value;
    if (typeof numericValue === "string") {
        numericValue = Number(numericValue);
    }
    if (typeof numericValue === "bigint") {
        if (numericValue < BigInt(minimum) || numericValue > BigInt(maximum)) {
            fail(path, `expected an integer in range [${minimum}, ${maximum}]`);
        }
        if (numericValue > BigInt(Number.MAX_SAFE_INTEGER) || numericValue < BigInt(Number.MIN_SAFE_INTEGER)) {
            fail(path, "JSON encoding cannot safely represent integers outside the JavaScript safe integer range");
        }
        numericValue = Number(numericValue);
    }
    if (typeof numericValue !== "number" || !Number.isInteger(numericValue) || numericValue < minimum || numericValue > maximum) {
        fail(path, `expected an integer in range [${minimum}, ${maximum}]`);
    }
    return numericValue;
}

function normalizeEnum(enumName, value, path) {
    const enumDefinition = ENUM_TYPES[enumName];
    if (!enumDefinition) {
        fail(path, `unknown enum ${enumName}`);
    }
    let numericValue = value;
    if (typeof numericValue === "string") {
        if (!hasOwn(enumDefinition, numericValue)) {
            fail(path, `unknown enum value ${numericValue} for ${enumName}`);
        }
        numericValue = enumDefinition[numericValue];
    }
    numericValue = normalizeInteger(numericValue, path, -0x80000000, 0xffffffff);
    if (!Object.values(enumDefinition).includes(numericValue)) {
        fail(path, `unknown enum value ${numericValue} for ${enumName}`);
    }
    return numericValue;
}

function defaultScalarValue(field) {
    switch (field.kind) {
    case "enum":
        return 0;
    case "scalar":
        switch (field.type) {
        case "bool":
            return false;
        case "string":
        case "bytes":
            return "";
        default:
            return 0;
        }
    default:
        return undefined;
    }
}

function normalizeScalar(field, value, path) {
    switch (field.type) {
    case "bool":
        return normalizeBoolean(value, path);
    case "string":
        return normalizeString(value, path);
    case "bytes":
        return normalizeBytes(value, path);
    case "uint32":
    case "fixed32":
        return normalizeInteger(value, path, 0, 0xffffffff);
    case "int32":
    case "sint32":
    case "sfixed32":
        return normalizeInteger(value, path, -0x80000000, 0x7fffffff);
    case "uint64":
    case "fixed64":
        return normalizeInteger(value, path, 0, Number.MAX_SAFE_INTEGER);
    case "int64":
    case "sint64":
    case "sfixed64":
        return normalizeInteger(value, path, Number.MIN_SAFE_INTEGER, Number.MAX_SAFE_INTEGER);
    default:
        fail(path, `unsupported scalar type ${field.type}`);
    }
}

function normalizeFieldValue(field, value, path) {
    switch (field.kind) {
    case "scalar":
        return normalizeScalar(field, value, path);
    case "enum":
        return normalizeEnum(field.type, value, path);
    case "message":
        return normalizeMessage(field.type, value, path);
    default:
        fail(path, `unsupported field kind ${field.kind}`);
    }
}

function normalizeMessage(typeName, value, path = typeName) {
    const definition = MESSAGE_TYPES[typeName];
    if (!definition) {
        fail(path, `unknown message type ${typeName}`);
    }

    const input = value === undefined || value === null ? {} : value;
    if (!isPlainObject(input)) {
        fail(path, "expected an object");
    }

    const knownFields = FIELD_NAME_LOOKUP.get(typeName);
    for (const inputField of Object.keys(input)) {
        if (!knownFields.has(inputField)) {
            fail(`${path}.${inputField}`, "unknown field");
        }
    }

    for (const oneof of definition.oneofs) {
        let presentCount = 0;
        for (const fieldName of oneof.fields) {
            if (fieldPresent(input, fieldName)) {
                presentCount += 1;
            }
        }
        if (presentCount > 1) {
            fail(path, `oneof ${oneof.name} has multiple values set`);
        }
    }

    const result = {};
    for (const field of definition.fields) {
        const present = fieldPresent(input, field.name);
        const fieldPath = `${path}.${field.name}`;

        if (field.repeated) {
            const listValue = present ? input[field.name] : [];
            if (!Array.isArray(listValue)) {
                fail(fieldPath, "expected an array");
            }
            result[field.name] = listValue.map((item, index) => normalizeFieldValue(field, item, `${fieldPath}[${index}]`));
            continue;
        }

        if (present) {
            result[field.name] = normalizeFieldValue(field, input[field.name], fieldPath);
            continue;
        }

        if (!field.has_presence) {
            result[field.name] = defaultScalarValue(field);
        }
    }

    return result;
}

function validateMessage(typeName, value) {
    try {
        normalizeMessage(typeName, value);
        return true;
    } catch {
        return false;
    }
}

function assertValidMessage(typeName, value) {
    normalizeMessage(typeName, value);
}

class MessageHasher {
    constructor() {
        this.hash = crypto.createHash("sha256");
    }

    feed(buffer) {
        this.hash.update(buffer);
    }

    feedUint8(value) {
        const buffer = Buffer.alloc(1);
        buffer.writeUInt8(value, 0);
        this.feed(buffer);
    }

    feedUint32(value) {
        const buffer = Buffer.alloc(4);
        buffer.writeUInt32BE(value >>> 0, 0);
        this.feed(buffer);
    }

    feedInt32(value) {
        const buffer = Buffer.alloc(4);
        buffer.writeInt32BE(value | 0, 0);
        this.feed(buffer);
    }

    feedUint64(value) {
        const buffer = Buffer.alloc(8);
        buffer.writeBigUInt64BE(BigInt.asUintN(64, BigInt(value)), 0);
        this.feed(buffer);
    }

    feedBool(value) {
        this.feedUint8(value ? 1 : 0);
    }

    feedBytes(value) {
        const buffer = Buffer.isBuffer(value) ? value : Buffer.from(value);
        this.feedUint32(buffer.length);
        this.feed(buffer);
    }

    tag(fieldNumber) {
        this.feedUint32(fieldNumber);
    }

    finalize() {
        return this.hash.digest();
    }
}

function hashScalar(field, value, hasher) {
    switch (field.type) {
    case "bool":
        hasher.feedBool(value);
        return;
    case "string":
        hasher.feedBytes(Buffer.from(value, "utf8"));
        return;
    case "bytes":
        hasher.feedBytes(Buffer.from(value, "base64"));
        return;
    case "uint32":
    case "fixed32":
        hasher.feedUint32(value);
        return;
    case "int32":
    case "sint32":
    case "sfixed32":
        hasher.feedInt32(value);
        return;
    case "uint64":
    case "fixed64":
        hasher.feedUint64(BigInt(value));
        return;
    case "int64":
    case "sint64":
    case "sfixed64":
        hasher.feedUint64(BigInt.asUintN(64, BigInt(value)));
        return;
    default:
        fail(field.type, "unsupported scalar type for hashing");
    }
}

function hashAny(value, hasher) {
    // Hash google.protobuf.Any by its type_url string, then hash the inner message fields.
    const typeUrl = value["@type"] || "";
    hasher.feedBytes(Buffer.from(typeUrl, "utf8"));
    const slash = typeUrl.lastIndexOf("/");
    const fullName = slash >= 0 ? typeUrl.substring(slash + 1) : typeUrl;
    // Strip package prefix to get the simple type name for schema lookup
    const dot = fullName.lastIndexOf(".");
    const typeName = dot >= 0 ? fullName.substring(dot + 1) : fullName;
    const definition = MESSAGE_TYPES[typeName];
    if (!definition) {
        fail(typeUrl, "cannot hash unknown Any type");
    }
    // Build a copy without @type for hashing as a regular message
    const inner = {};
    for (const key of Object.keys(value)) {
        if (key !== "@type") inner[key] = value[key];
    }
    hashMessageObject(typeName, inner, hasher);
}

function hashFieldValue(field, value, hasher) {
    switch (field.kind) {
    case "scalar":
        hashScalar(field, value, hasher);
        return;
    case "enum":
        hasher.feedUint32(value >>> 0);
        return;
    case "message":
        if (field.type === "Any") {
            hashAny(value, hasher);
            return;
        }
        hashMessageObject(field.type, value, hasher);
        return;
    default:
        fail(field.type, "unsupported field kind for hashing");
    }
}

function hashMessageObject(typeName, value, hasher) {
    const definition = MESSAGE_TYPES[typeName];
    for (const field of definition.fields) {
        if (field.name === "signature" && typeName === "RSPMessage") {
            // Signature fields are excluded from the hash — the hash is what gets signed.
            // Signing raw protobuf bytes instead would require a protobuf dependency in clients.
            continue;
        }

        if (field.repeated) {
            const listValue = value[field.name] || [];
            hasher.tag(field.number);
            hasher.feedUint32(listValue.length >>> 0);
            for (const item of listValue) {
                hashFieldValue(field, item, hasher);
            }
            continue;
        }

        if (field.has_presence && !fieldPresent(value, field.name)) {
            continue;
        }

        hasher.tag(field.number);
        hashFieldValue(field, value[field.name], hasher);
    }
}

function hashMessage(typeName, value) {
    const normalized = normalizeMessage(typeName, value);
    const hasher = new MessageHasher();
    hashMessageObject(typeName, normalized, hasher);
    return hasher.finalize();
}

const exported = {
    schema: Object.freeze(SCHEMA),
    constructors: {},
    validators: {},
    hashers: {},
    createMessage: normalizeMessage,
    validateMessage,
    assertValidMessage,
    hashMessage,
};

for (const [enumName, values] of Object.entries(ENUM_TYPES)) {
    exported[enumName] = Object.freeze({...values});
}

for (const typeName of Object.keys(MESSAGE_TYPES)) {
    const createName = `create${typeName}`;
    const validateName = `validate${typeName}`;
    const assertName = `assertValid${typeName}`;
    const hashName = `hash${typeName}`;

    exported[createName] = (value = {}) => normalizeMessage(typeName, value);
    exported[validateName] = (value) => validateMessage(typeName, value);
    exported[assertName] = (value) => assertValidMessage(typeName, value);
    exported[hashName] = (value) => hashMessage(typeName, value);

    exported.constructors[typeName] = exported[createName];
    exported.validators[typeName] = exported[validateName];
    exported.hashers[typeName] = exported[hashName];
}

module.exports = Object.freeze(exported);
