CLIENT_CPP_RSP_CLIENT_SOURCE = client/cpp/rsp_client.cpp
CLIENT_CPP_RSP_CLIENT_HEADER = client/cpp/rsp_client.hpp
CLIENT_CPP_RSP_C_API_SOURCE = client/cpp/rsp_c_api.cpp
CLIENT_CPP_RSP_C_API_HEADER = client/cpp/rsp_c_api.h
CLIENT_CPP_RSP_CLIENT_MESSAGE_SOURCE = client/cpp/rsp_client_message.cpp
CLIENT_CPP_RSP_CLIENT_MESSAGE_HEADER = client/cpp/rsp_client_message.hpp
CLIENT_CPP_EXPORT_HEADER = client/cpp/rsp_client_export.hpp