COMMON_BASE_TYPES_SOURCE = common/base_types.cpp
COMMON_BASE_TYPES_HEADER = common/base_types.hpp
COMMON_NODE_SOURCE = common/node.cpp
COMMON_NODE_HEADER = common/node.hpp
COMMON_KEYPAIR_SOURCE = common/keypair.cpp
COMMON_KEYPAIR_HEADER = common/keypair.hpp